--- #YAML:1.0
name:               Array-OrdHash
version:            1.02
abstract:           ordered associative array with array-like, hash-like and OO interface.
author:
    - Vladimir Surin <brexs@yandex.ru>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
